//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoggerDevice2 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The SD Card module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>The Ethernet ENC28 module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.EthernetENC28 ethernetENC28;
        
        /// <summary>The Breakout module using socket 18 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout breakout;
        
        /// <summary>The Breakout module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout breakout2;
        
        /// <summary>The USB Host module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBHost usbHost;
        
        /// <summary>The Breakout module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout breakout3;
        
        /// <summary>The Display NHVN module using sockets 15, 16 and 17 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayNHVN displayNHVN;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZRaptor Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZRaptor)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZRaptor();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.sdCard = new GTM.GHIElectronics.SDCard(9);
            this.ethernetENC28 = new GTM.GHIElectronics.EthernetENC28(11);
            this.breakout = new GTM.GHIElectronics.Breakout(18);
            this.breakout2 = new GTM.GHIElectronics.Breakout(13);
            this.usbHost = new GTM.GHIElectronics.USBHost(7);
            this.breakout3 = new GTM.GHIElectronics.Breakout(2);
            this.displayNHVN = new GTM.GHIElectronics.DisplayNHVN(15, 16, 17, Socket.Unused, Socket.Unused);
        }
    }
}
